[#78] Add AccessBox scheme
nspcc-dev/neofs-spec pull request #79
Opened 2022-09-06 12:35 UTC by KirillovDenis

close #78 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>

2022-09-06 14:44 UTC, EliChin requested changes
Please, pay attention to the English fixes suggested

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +S3 gateway have to authenticate user requests staying in [AWS spec](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html).
S3 gateway has to authenticate user requests regarding

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +1. User use the [neofs-s3-authmate](https://github.com/nspcc-dev/neofs-s3-gw/blob/master/docs/authmate.md)
A user uses

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +2. Authmate forms "AccessBox" object (see the next section) and put it into NeoFS.
Authmate forms an "AccessBox" object (see the next section) and puts it into NeoFS.

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +3. Authmate output contains credentials (`access_key_id` and `secret_access_key`) that can be used with AWS CLI for example.
AWS CLI, for example.

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +4. User send request to NeoFS S3 Gateway using standard AWS tool.
4. The user sends a request

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +5. S3 Gateway get "AccessBox" from NeoFS by `access_key_id` and fetch Bearer Token from it.
S3 Gateway gets ... and fetches

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +6. S3 Gateway use fetched Bearer token to send a request to NeoFS on behalf of user.
uses the fetched ... of the user

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +It contains encrypted  Bearer token (`BT`), Session tokens (`STs`) and `secret_access_key`.
an encrypted Bearer Token ... a `secret_access_key`.

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +The credentials are formed by following steps:
by the following

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +1. User provides to Authmate `BT`, `STs` and `s3gw_public_key_k`(public keys of gates that will be able
provides Authmate with `BT` ... (the public keys of the gates that will be able

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +to handle credentials) that will be used when user sends requests via S3 Gateway.
when the user

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +   1. Generates `secret_access_key` (it's 32 random bytes), and P256 (secp256r1) key pair
Generates a `secret_access_key` (it's 32 random bytes) and a P256 (secp256r1) key pair

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +   2. Form `tokens` protobuf struct that contains `BT`, `STs`, `secret_access_key`
Forms a `tokens` protobuf struct

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +   3. For each `s3gw_public_key_k` derives symmetric key `symmetric_key_k`
derives a symmetric key

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +      encrypt `tokens` (`encrypted_tokens_k = encrypt(tokens.to_bytes(), secret_key_k, nonce_k)`).
encrypts

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +   4. For each `encypted_tokens_k` forms struct `gate_k` that contains `encrypted_tokens_k` and `s3gw_public_key_k`.
a struct called `gate_k`

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +   5. Form final binary object `AccessBox` that contains `authmate_public_key`, `gate_1`, ..., `gate_k`.
Forms the final

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +   6. Put `AccessBox` object to NeoFS and save its address `CID/OID` as `access_key_id`.
Puts the `AccessBox` object to NeoFS and saves its address

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +   7. Return pair (`access_key_id`, `access_secret_key`) to user.
Returns the pair (`access_key_id`, `access_secret_key`) to the user.

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +On getting request S3 Gateway:
On getting a request, S3 Gateway:

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +1. Fetch `access_key_id` from `Authorization` header.
Fetches the `access_key_id` from the `Authorization` header.

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +2. Get `AccessBox` from NeoFS by address (recall `access_key_id` is `CID/OID`)
Gets

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +was found by matching `s3gw_public_key_k` in `gate_k` struct.
has been found

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +4. Check signature of initial request using `secret_access_key` from `tokens` struct.
Checks the signature of the initial request

2022-09-06 14:44 UTC, EliChin commented on 04-gates/00-gates.md
> +5. Use `BT` and `STs` to perform requests to NeoFS.
Uses

2022-09-07 07:11 UTC, EliChin approved these changes

2022-09-07 07:12 UTC, realloc approved these changes

2022-09-07 07:12 UTC, merged